import {MODEL_INFO} from './engine.js';
import {EXPANSION_THRESHOLD,GREEN_END,YELLOW_AT,OPEN_FILL_MIN,SQUARE_MIN_OPEN,RING_GAIN,RING_MIN_OPEN,EXTRA_AIR_RING_FRACTION} from './map-color.js';
import {PLEURAL_READOUT_INFO} from './pleural-readout.js';
const percent=x=>Math.round(x*100),ref=MODEL_INFO.referenceTranspulmonaryPressure,cut=EXPANSION_THRESHOLD;
export const WORKED_EXAMPLES={
 opening:{fBefore:.5,fAfter:.6,vOpen:8},stretch:{f:.5,vOpenBefore:8,vOpenAfter:10},
 ratio:{reference:6,current:10.2},share:{total:100,open:60,markedOpen:20},
 emptying:{start:6,peak:40,end:6,smallEnd:3},
 rc:[{tau:1,te:2},{tau:2,te:2},{tau:1,te:4/3}],
 pressure:{paw:25,ppl:10,resistiveDrop:3},pes:{mean:10,gradient:5,depMean:.5,dEs:PLEURAL_READOUT_INFO.esophagealDependency,offset:0}
};
const e=WORKED_EXAMPLES;
export const COMMON_NUMBERS=[
 {title:'Pressure inside minus pressure outside',formula:'Pressure across the lung = pressure inside the airspaces − pleural pressure',example:`Illustrative numbers: inside ${e.pressure.paw} − outside ${e.pressure.ppl} = ${e.pressure.paw-e.pressure.ppl} cmH2O across the lung. With the same inside pressure, a higher outside pressure leaves less pressure across the lung.`,meaning:'Pleural pressure is the pressure surrounding the lung. In the recruitment view, no resistance-related pressure drop is modeled, so airway pressure equals airspace pressure.',scope:`During flow, airway pressure also includes the push through the airways. If airway pressure is ${e.pressure.paw} and the pressure drop to a region is ${e.pressure.resistiveDrop}, its airspace pressure is ${e.pressure.paw-e.pressure.resistiveDrop}; subtracting pleural ${e.pressure.ppl} gives ${e.pressure.paw-e.pressure.resistiveDrop-e.pressure.ppl}, not ${e.pressure.paw-e.pressure.ppl} cmH2O. Zero total flow need not mean zero flow between regions.`},
 {title:'Why simulated Pes differs from the mean',formula:'Model Pes = mean pleural pressure + gradient × (sample position − mean position) + assumed offset',example:`Illustrative supine example: ${e.pes.mean} + ${e.pes.gradient} × (${e.pes.dEs} − ${e.pes.depMean}) + ${e.pes.offset} = ${(e.pes.mean+e.pes.gradient*(e.pes.dEs-e.pes.depMean)).toFixed(2)} cmH2O. The sample is toward the back of this schematic lung; the position is assumed, not measured.`,meaning:'The mean averages the whole modeled tissue. Simulated Pes samples one chosen position. Prone changes the assumed gradient; it does not move this sampling position.',scope:'Because the gradient and sample position are fixed within a breath, simulated Pes rises and falls by exactly the same amount as mean pleural pressure. This simple model has no balloon, esophageal-wall, or measurement mechanics.'}
];
export const RECRUITMENT_COPY={
 title:'How to read opening and stretching',
 watch:'Opening more lung tissue and stretching open tissue are different things. Watch for both: are more areas opening, are the open areas expanding more, or is both happening?',
 sections:[
  {title:'A bigger dot means more air',text:'Each dot is one lung region, and a region can be partly open. Its dot can grow because more tissue opens, because the open part expands, or both. Dot size alone cannot separate those changes.'},
  {title:'Grey, green, yellow and red',text:'Grey means much of the region is poorly aerated. Green means it contains ventilated tissue, not necessarily healthy tissue. Yellow toward red means the open part is more expanded. Red is this model’s high-stretch marker; it does not show tissue damage.'},
  {title:'Dashed ring: more tissue opened',text:'The region has opened more since this breath began. Watch the breath out: does that additional opening remain, or does it fade? Small changes may fall below the ring’s display threshold.'},
  {title:'Red square: a stretched open part',text:'At the end of the breath in, the open part crossed the assumed expansion cutoff. A mostly grey dot can still have a square: a small open part may be highly expanded.'},
  {title:'What the stretch percentage counts',text:'It counts open tissue above the cutoff as a share of all tissue in the model. It is not the percentage of lung that is injured. No red is not proof that a real lung would be safe.'},
  {title:'Pressure around the lung matters too',text:'Airway pressure alone is not the whole story. The pressure just outside the lung is pleural pressure. In this view, subtracting it from airway pressure gives the pressure across the lung. Some of the applied pressure also moves the chest wall.'},
  {title:'What simulated Pes means',text:'The purple dot samples the model’s surrounding pressure at one assumed position toward the back. It is different from the whole-lung mean, but rises and falls by the same amount in this simplified model. It is not a clinical balloon measurement.'},
  {title:'One calculated breath, repeated',text:'The animation repeats one calculated breath. Smooth shrinking and loop transitions help you watch it; they do not calculate new breaths or accumulating injury. Numbers pause during these visual blends because no intermediate pressure states were calculated.'}
 ],
 numbers:[
  {title:'Two ways a region can hold more air',formula:'Air in a region = open fraction × volume if that whole region were open',example:`Illustrative numbers: ${e.opening.fBefore} × ${e.opening.vOpen} = ${e.opening.fBefore*e.opening.vOpen} mL. Opening from 50% to 60% gives ${e.opening.fAfter} × ${e.opening.vOpen} = ${e.opening.fAfter*e.opening.vOpen} mL. Keeping 50% open but expanding its fully-open volume from 8 to 10 mL gives ${e.stretch.f} × ${e.stretch.vOpenAfter} = ${e.stretch.f*e.stretch.vOpenAfter} mL.`,meaning:'In symbols: Vgas = f × Vopen. f is the part of this region’s tissue that is open, from 0 to 1. Vopen is the volume the whole region would hold if open at the current pressure. Increasing f is opening; increasing Vopen is expansion of open tissue.',scope:'These made-up numbers show the difference. They are not the displayed patient’s values or recommended settings.'},
  {title:'The color ratio compares the same amount of open tissue',formula:`Expansion ratio = Vopen(now) ÷ Vopen(at lung-distending pressure ${ref} cmH2O)`,example:`Illustrative fully-open volumes: ${e.ratio.current} ÷ ${e.ratio.reference} = ${(e.ratio.current/e.ratio.reference).toFixed(2)}. That is 70% larger than the reference and above the ${cut} cutoff. A ratio of ${cut} means ${percent(cut-1)}% larger, not ${percent(cut-1)}% newly opened or injured.`,meaning:`Green reaches ${GREEN_END}; yellow is ${YELLOW_AT}; full red begins at ${cut}. The ratio does not use the region’s current gas volume f × Vopen, so changing how much tissue is open does not get counted as extra stretching.`,scope:'These are assumed display levels, not established injury thresholds. The reference is not resting lung volume or FRC, and this ratio is not tidal volume divided by FRC.'},
  {title:'A percentage of all modeled tissue, not of injured lung',formula:`High-stretch share = Σ [region’s tissue share × open fraction at end inspiration × (ratio > ${cut})]`,example:`Imagine ${e.share.total} equal amounts of tissue. At the end of the breath in, ${e.share.open} amounts are open and ${e.share.markedOpen} of those are above the cutoff. The reported share is ${e.share.markedOpen}/${e.share.total} = ${percent(e.share.markedOpen/e.share.total)}%, not ${e.share.markedOpen}/${e.share.open} ≈ ${percent(e.share.markedOpen/e.share.open)}%. A region representing 10 amounts at 50% open contributes 5 open amounts, not 10.`,meaning:'Σ means add the regions together. Each region’s tissue share is its weight w; all weights sum to 1. The open fraction f is sampled at the end of inspiration for this count. Dots do not all have equal tissue weight.',scope:'The separate “open tissue before the breath” number uses an earlier snapshot. Do not divide the two displayed percentages to estimate an injured fraction.'},
  {title:'Exactly when a ring or square appears',formula:`Grey: open fraction ≤ ${OPEN_FILL_MIN}. Dashed ring: opening gain > ${RING_GAIN} and open fraction > ${RING_MIN_OPEN}. Red square: end-inspiration ratio > ${cut} and open fraction > ${SQUARE_MIN_OPEN}.`,example:`A region that is 25% open stays grey, but if its open portion has a ratio of 1.70 it can have a red square at the end of inspiration. Its small open portion counts toward the stretch percentage.`,meaning:`Opening gain is compared with the start of this breath. ${percent(RING_GAIN)} percentage points is the ring’s display threshold, not a biological opening threshold.`,scope:`Color changes continuously and reaches full red at ${cut}; the numeric count and square use strictly above ${cut}. Very small open portions can count numerically without getting a visible square.`},
  ...COMMON_NUMBERS
 ]
};
export const AIRFLOW_COPY={
 title:'How to read air moving in and out',
 watch:'Watch what happens when the ventilator stops delivering the breath. Air needs time to leave. Does the extra air clear before the next breath, or is some still left?',
 sections:[
  {title:'Air in makes dots bigger; air out makes them smaller',text:'Regions taking in air grow; regions releasing air shrink. Some respond faster than others. This view keeps the amount of open tissue fixed, so changes in dot size show air movement, not new tissue opening or collapsing.'},
  {title:'A region does not have to become empty',text:'At PEEP, an open region still holds a resting amount of air. “Extra air” means air above that resting amount. It can include air carried over from an earlier breath, not just air added during this one.'},
  {title:'Blue ring: extra air is still present',text:'A blue ring during early breathing out is expected. At the end of breathing out, a ring means more than a tenth of that region’s extra air at the end of the breath in remains. No ring can still mean a small amount remains below the display cutoff.'},
  {title:'Resistance and time determine how fast air leaves',text:'More airway resistance slows emptying. A faster breathing rate leaves less time to breathe out, and also less time to breathe in. The regions share airways and a chest wall, so they do not each empty independently.'},
  {title:'This is air movement, not recruitment',text:'Grey and green still describe how much tissue is open, but that amount is held constant here. Yellow/red stretch colors are off because this simpler airflow model does not calculate the same regional expansion ratio.'}
 ],
 numbers:[
  {title:'Extra air is measured from a resting reference',formula:'Extra air = current gas volume − relaxed gas volume at PEEP',example:`Illustrative repeating breath: ${e.emptying.start} mL of extra air at the start, ${e.emptying.peak} mL at the end of inspiration, and ${e.emptying.end} mL at the end. This breath added and released ${e.emptying.peak-e.emptying.start} mL, but ${e.emptying.end} mL of extra air still remains.`,meaning:'The relaxed reference is the gas volume at PEEP with the same tissue held open and enough time for flow to settle. It is not zero volume and not necessarily the volume where this breath started.',scope:'A breath can release as much air as it received and still leave extra air above this relaxed level.'},
  {title:'The released percentage and the blue ring',formula:'Share of extra air released = (extra air at the end of the breath in − extra air at end expiration) ÷ extra air at the end of the breath in',example:`(${e.emptying.peak} − ${e.emptying.end})/${e.emptying.peak} = ${percent((e.emptying.peak-e.emptying.end)/e.emptying.peak)}% released. ${e.emptying.end}/${e.emptying.peak} = ${percent(e.emptying.end/e.emptying.peak)}% remains: above the ${percent(EXTRA_AIR_RING_FRACTION)}% blue-ring cutoff. If only ${e.emptying.smallEnd} mL remains, ${e.emptying.smallEnd}/${e.emptying.peak} = ${(100*e.emptying.smallEnd/e.emptying.peak).toFixed(1)}%: no ring at that moment, but not zero extra air.`,meaning:'The ring uses the current regional volume at every frame. The percentage under the map summarizes the whole model at the end of expiration. Each uses its own peak extra-air reference.',scope:'This is different from expired tidal volume divided by inspired tidal volume. Air moving between linked regions can also make an individual region’s fraction exceed 100% or fall below zero.'},
  {title:'A faster rate shortens both parts of the breath',formula:'Cycle time = 60 ÷ breaths/min. In this model, breathing in uses ⅓ and breathing out uses ⅔.',example:'20/min: cycle 3 s, in 1 s, out 2 s. 30/min: cycle 2 s, in about 0.67 s, out about 1.33 s.',meaning:'At the same requested volume, less inspiratory time needs faster incoming flow. Less expiratory time gives extra air less time to leave.',scope:'These are model timing assumptions, not a recommended rate or inspiratory-to-expiratory ratio.'},
  {title:'A simpler example: one isolated region',formula:'Time constant τ = resistance R × compliance C. Remaining extra-air fraction = exp(−time out ÷ τ).',example:`Illustrative values: τ = 1 s and 2 s out leaves about ${percent(Math.exp(-2))}%. τ = 2 s with the same 2 s out leaves about ${percent(Math.exp(-1))}%. τ = 1 s with 1.33 s out leaves about ${percent(Math.exp(-4/3))}%.`,meaning:'Resistance describes how hard it is for air to move. Compliance describes how much volume changes per pressure change. A larger time constant means slower emptying in this isolated example.',scope:'The real simulation links regions through shared airways and chest-wall recoil. Do not plug its live values into this isolated formula as an exact prediction. Doubling the central-resistance slider does not double every region’s own time constant.'},
  ...COMMON_NUMBERS
 ]
};
export const ELI5_COPY={
 recruitment:'Picture a patch of lung as little air pockets. Opening more pockets is different from making open pockets bigger. Bigger dot = more air. Grey means less air-filled tissue; green means ventilated, not necessarily healthy. Yellow/red marks more stretching of the open part. A dashed ring marks more opening; a red square marks high expansion at the end of the breath in. Red is not proof of damage.',
 airflow:'Picture air pockets connected to straws. Here, how much tissue is open stays the same. Air in makes dots grow; air out makes them shrink. More resistance slows emptying; faster breathing leaves less time. While breathing out, a blue ring means more than a tenth of the extra air at the end of the breath in is still there. The pockets do not have to lose every bit of air at PEEP.'
};
export const PHASE_COPY={
 recruitment:{'Before inspiration':'Before the breath: watch which poorly aerated regions open as pressure rises.','Inspiration':'Dots grow because more tissue opens, open tissue expands, or both. Rings mark more opening; yellow/red tracks expansion.','End inspiration':'End of the breath in: look for tissue opening and open tissue stretching more at the same time.','Pressure release':'Pressure returns to PEEP. This view has no airway resistance, so calculated gas volume drops immediately; the smooth shrinking is visual.','Expiration':'Watch which regions stay open at PEEP and which lose some of that opening.','End expiration':'End of this recorded breath. Compare it with the start; the model may not have settled into identical breaths yet.'},
 airflow:{'Before inspiration':'Some extra air may still be here from earlier breaths. The amount of open tissue stays fixed.','Inspiration':'Air takes pressure to move through the airways. Regions receiving it grow.','End inspiration':'Air is still coming in here. Peak airway pressure includes resistance; it is not a measured plateau.','Start expiration':'The ventilator drops pressure to PEEP. Air now takes time to leave through the airways.','Expiration':'Watch the dots shrink and blue rings fade as extra air leaves.','End expiration':'A blue ring here means extra air is still above the display cutoff. Check the flow and the amount left.'}
};
