export const LESSONS = {
  recruitment: {name:'PEEP and recruitability',kinds:['high','low'],baseline:{peep:8,vt:6,rr:20,pbw:70},adjustment:{peep:12},objective:'See why the same PEEP increase can open a lot of closed tissue in one lung but mostly stretch tissue that is already open in another.',prediction:'Before applying: which patient will have more tissue open before the breath, and could the high-stretch tissue share rise in both?',reflection:'Compare how much extra tissue opened with how much high-stretch tissue appeared in A and B. A lower driving pressure alone does not show the change helped, because tissue that is already open can still be stretched more.',instruction:'Raise PEEP from 8 to 12 in both lungs. A and B differ in how much pressure their closed tissue needs before it opens (assumed values). Compare open tissue before the breath, driving pressure and the high-stretch tissue share: the share of all model tissue that is open and stretched past the assumed cutoff at end inspiration.',numbers:'Illustrative numbers, not current patient data. Gas in a region = f × Vopen, where f is how much of the region is open and Vopen is its volume if fully open. A region with f = 0.5 and Vopen = 10 mL holds 5 mL. Opening more raises f (0.7 × 10 = 7 mL). Stretching raises Vopen (0.5 × 14 = 7 mL). Both add gas, so total volume alone cannot say which one happened. High-stretch share example: of 100 tissue units, 60 are open at end inspiration and 20 of those are past the cutoff. The share is 20 / 100 = 20% of ALL tissue, not 20 / 60 = 33% of the open tissue.'},
  wall: {name:'Chest-wall pressure',kinds:['high','wall'],baseline:{peep:8,vt:6,rr:20,pbw:70},adjustment:{peep:12},objective:'Separate the part of airway pressure that pushes against the chest wall from the part that actually stretches the lung.',prediction:'Before applying: if B has a higher airway pressure, does that necessarily mean more pressure across B’s lung tissue (transpulmonary pressure)?',reflection:'In each patient, subtract the pressure around the lung (pleural pressure) from the airway pressure. Explain how a heavier chest-wall load changes what airway pressure tells you about the lung.',instruction:'A and B share the same lung assumptions. B has a stiffer chest wall and a higher starting pressure around the lung. Compare airway pressure with mean transpulmonary pressure (airway pressure minus the average pressure around the lung). Airway pressure alone mixes the lung’s share with the chest wall’s share.',numbers:'Illustrative numbers, not current patient data. Pressure across lung tissue = airway − mean pleural. Example: 25 − 10 = 15 cmH2O. This assumes no pressure is lost to airflow resistance, which holds in the quasi-static model but not for flowing air. The mean pleural value is a model average, not a measurement. Driving pressure is a different subtraction: plateau 25 − PEEP 8 = 17 cmH2O.'},
  volume: {name:'Tidal volume and regional distension',kinds:['high','high'],baseline:{peep:8,vt:6,rr:20,pbw:70},adjustment:{vt:8},objective:'Explain how a bigger breath changes the pressure the whole lung needs and how much open tissue gets stretched, in identical lungs.',prediction:'Before applying: where will the extra air go, and what may happen to driving pressure and to the high-stretch tissue share?',reflection:'Check the volume actually delivered, driving pressure and the high-stretch tissue share together. Explain why a whole-lung compliance that looks unremarkable cannot rule out heavy stretch in some regions.',instruction:'Both patients have identical lungs. Raise tidal volume from 6 to 8 mL/kg PBW (predicted body weight). Watch the delivered volume, driving pressure and the high-stretch tissue share: the part of all model tissue that is open and stretched past the assumed cutoff at end inspiration.',numbers:'Illustrative numbers, not current patient data. Extra volume goes mostly into tissue that is already open, which stretches it. Gas in a region = f × Vopen, so stretching raises Vopen without changing f. Stretch ratio = Vopen ÷ the region’s volume at 5 cmH2O. If Vopen is 10.2 mL and the 5 cmH2O volume is 6 mL, the ratio is 10.2 / 6 = 1.70, above the 1.65 cutoff. This ratio ignores f, which is how much of the region is open. Compliance example: 420 mL ÷ 14 cmH2O = 30 mL/cmH2O. This is not a target.'},
  'pressure-drive': {name:'Airway vs external pressure drive',kinds:['high','high'],baseline:{peep:8,vt:6,rr:20,pbw:70},adjustment:{'pressure-drive':'external'},objective:'Tell apart where the breathing pressure is applied from the pressure that actually stretches the lung.',prediction:'Before applying: if the same breath is pulled in by negative pressure around the body, which pressures change and which stay the same?',reflection:'Compare the average pressure around the lung with the pressure across lung tissue and the high-stretch tissue share. Explain how the pressure across lung tissue can stay the same while airway and pleural pressures differ.',instruction:'After applying the change, both patients get the same requested breath from an ideal uniform-transmission external drive: negative pressure around the body instead of positive pressure at the airway. Compare each with its positive-pressure baseline. Airway pressure readouts become zero and the pressure around the lung shifts lower. Pressure across lung tissue, volumes and open tissue stay the same by construction. This does not show that either way of delivering the breath is preferable.',numbers:'Illustrative numbers, not current patient data. Positive-pressure breath: airway 25, mean pleural 10, so 25 − 10 = 15 cmH2O across lung tissue. Ideal external drive of the same breath: external −25, airway 0, and the whole shift passes to the pleural space (ideal uniform transmission), so pleural = 10 − 25 = −15. Across lung tissue: 0 − (−15) = 15 cmH2O, unchanged. Only where the pressure is applied has changed.'},
  prone: {name:'Prone posture and the pleural gradient',kinds:['high','low'],baseline:{peep:8,vt:6,rr:20,pbw:70},adjustment:{posture:'prone'},objective:'Explain how reversing and flattening an assumed top-to-bottom gradient in the pressure around the lung can move pressure between regions while each region’s opening pressure stays fixed.',prediction:'Before applying: which patient will show a change in open tissue before the breath, and could high-stretch tissue at end inspiration change too?',reflection:'Compare each patient’s open tissue and high-stretch tissue share. Which results depend on the assumed gradient, and which on the fixed opening pressures of each region?',instruction:'After applying the change, both lungs enter an assumed prone state. The assumed gradient in the pressure around the lung is reversed and halved. The average pressure around the lung at the same gas volume stays the same. Each region’s opening pressure and blood-flow weighting stay tied to its fixed anatomical position. The halving factor is an assumption, not a measurement, and the outcome depends on the lung type. This does not predict how a real patient would respond.',numbers:'Illustrative numbers, not current patient data. Pressure around the lung at a region = mean + g × (region position − mean position), with position 0 at the front and 1 at the back. Take mean 5 cmH2O, mean position 0.5 and a back region at 0.8. Supine with g = +6: 5 + 6 × 0.3 = 6.8. Prone with g = −3 (reversed and halved): 5 − 3 × 0.3 = 4.1. The mean stays 5 because the gradient is a straight line around the same average. With airway pressure 20, the back region has 20 − 6.8 = 13.2 across its tissue supine and 20 − 4.1 = 15.9 prone.'},
  'chest-load': {name:'Static chest-wall load',kinds:['healthyDependent','high'],baseline:{peep:8,vt:6,rr:20,pbw:70},adjustment:{'chest-load':5},objective:'Show that a static push on the lung from outside acts separately from chest-wall stiffness, and that its effect depends on how full the lung is to start with.',prediction:'Before applying: will a static 5 cmH2O load change the gas volume left after breathing out in the same way in both patients?',reflection:'Compare gas volume, open tissue and driving pressure in A and B. Explain why compliance can rise or fall depending on where each lung starts.',instruction:'A chest load of 5 cmH2O adds the same static offset to the pressure around the lung everywhere. It is not a weight and not a change in chest-wall stiffness: chest-wall elastance is unchanged. Compliance can rise or fall depending on the starting volume and how much tissue is open.',numbers:'Illustrative numbers, not current patient data. With airway 8 and pleural 3, the pressure across lung tissue is 8 − 3 = 5 cmH2O. A 5 cmH2O load makes pleural 8, so the same airway pressure gives 8 − 8 = 0 across the tissue until the lung settles at a new volume. Compliance = volume ÷ driving pressure. The same 420 mL breath at 14 cmH2O is 30 mL/cmH2O; at 12 it is 35 and at 17 it is 24.7. These values are not targets, and the direction depends on the starting volume.'},
  'healthy-dependent': {name:'Dependent closure in otherwise healthy mechanics',kinds:['healthy','healthyDependent'],baseline:{peep:2,vt:6,rr:20,pbw:70},adjustment:{peep:10},objective:'Illustrate how an assumed small tendency of the lowest (dependent) tissue to close can respond to PEEP in lungs whose other mechanics are normal.',prediction:'Before applying: will raising PEEP change B’s open tissue and driving pressure more than A’s?',reflection:'Compare open tissue, opening during the breath and driving pressure in A and B. Explain why this is a teaching construct and not a statement that dependent regions are closed in every healthy lung.',instruction:'Patient B has the same seeded healthy mechanics plus a fixed tendency for dependent tissue to close. This is a teaching model with assumed constants, not a clinical calibration; dependent closure is not always present in healthy lungs.',numbers:'Illustrative numbers, not current patient data. Opening during the breath = sum of weight × max(0, open at end inspiration − open before the breath). A region with weight 0.10 that goes from 0.30 open to 0.80 open adds 0.10 × 0.50 = 0.05, which is 5 percentage points of all tissue. A region that becomes less open adds 0, because negative changes are not subtracted.'}
};
export const METRIC_HELP = {
  delivery:'How much air the breath actually moved in, compared with how much was requested. Check this first, because a pressure ceiling can stop the full breath from being delivered.',
  eelv:'The air present before this recorded breath starts. It can be higher because more tissue is open, because the open part has expanded, or both. It is not a measure of benefit.',
  pplat:'The airway pressure at the end of the breath. It has to push against both the lung and the chest wall. This model does not perform a clinical inspiratory hold, and with no airflow resistance in this mode it equals the pressure inside the airspaces.',
  dp:'Driving pressure is the end-of-breath airway pressure minus PEEP. For the same delivered volume, a lower value means the lung and chest wall needed less pressure to take the breath. Some tissue can still be stretched more.',
  crs:'Respiratory compliance is the delivered volume divided by the driving pressure: how much volume each cmH2O adds. A higher value means the same pressure moves more air in this model. It does not prove a safer setting.',
  openEE:'The share of all model tissue that is open before the breath starts. A higher value means more tissue stays open between breaths. It does not predict oxygenation or clinical outcome.',
  cyclic:'Adds up the tissue that opened more between the start and end of the breath in. Areas that became less open are not subtracted from this number. Watch the breath out to see whether the new opening remains; this number does not measure injury.',
  over:'The share of all model tissue that is both open and stretched past a set cutoff at the end of the breath. It marks possible excessive stretch in the model only, shown in red on the lung map. It does not predict or detect tissue damage, and no red does not mean safe.',
  closedPerfusion:'Closed tissue counted more heavily where a fixed anatomical dorsal weighting gives it more weight. In a prone experiment the weighting stays tied to the anatomy, so it is not always gravitationally dependent. It does not predict shunt or gas exchange.',
  transrespDP:'The change in airway-minus-external pressure from the end of a breath out to the end of the breath. In tank mode this is not the airway driving pressure.',
  transrespCrs:'Delivered volume divided by the airway-minus-external pressure change. This ideal uniform-transmission model keeps the lung mechanics the same at a matched drive.'
};
export const METRIC_NUMBERS = {
  delivery:'Illustrative numbers, not current patient data. Delivered = end-inspiratory volume − volume at breath start. Example: 2,400 − 1,980 = 420 mL, compared with 420 mL requested (6 mL/kg × 70 kg PBW).',
  eelv:'Illustrative numbers, not current patient data. EELV = sum over regions of f × Vopen, where f is how much of a region is open and Vopen is its volume if fully open. A region with f = 0.5 and Vopen = 10 mL holds 5 mL. Opening more (f = 0.7, Vopen = 10) gives 7 mL. Stretching more (f = 0.5, Vopen = 14) also gives 7 mL, so volume alone cannot say which happened.',
  pplat:'Illustrative numbers, not current patient data. Plateau = airway pressure at end inspiration, treated as quasi-static (no airflow and no resistive drop). Transpulmonary = airway − mean pleural. Example: 25 − 10 = 15 cmH2O across lung tissue, assuming no resistive pressure drop. The mean pleural value is a model average over tissue, not a measurement.',
  dp:'Illustrative numbers, not current patient data. Driving pressure = plateau − PEEP. Example: 25 − 8 = 17 cmH2O. Mean pleural pressure is a different quantity from PEEP and does not enter this subtraction.',
  crs:'Illustrative numbers, not current patient data. Crs = delivered volume ÷ driving pressure. Example: 420 mL ÷ 14 cmH2O = 30 mL/cmH2O. This is an illustration, not a target.',
  openEE:'Illustrative numbers, not current patient data. Open before the breath = sum over regions of w × f, where w is the region’s share of all tissue and f is its open fraction. Example: w = 0.5, 0.3, 0.2 with f = 0.8, 0.5, 0.1 gives 0.40 + 0.15 + 0.02 = 0.57, or 57%.',
  cyclic:'Illustrative numbers, not current patient data. Opening during the breath = sum of w × max(0, f at end inspiration − f before the breath). Example: w = 0.2 and f rising from 0.30 to 0.80 gives 0.2 × 0.5 = 0.10, or 10 percentage points. A region that becomes less open adds 0.',
  over:'Illustrative numbers, not current patient data. High-stretch % = sum of w × f_EI × [ratio > 1.65], where f_EI is the open fraction at end inspiration and ratio = Vopen ÷ the region’s volume at 5 cmH2O across its tissue. It is a fraction of ALL model tissue, not of the open tissue and not of an injured lung. Example: of 100 tissue units at end inspiration, 60 are open and 20 of those have ratio > 1.65, so the share is 20 / 100 = 20% (not 20 / 60 = 33%). Ratio example for a fully open region: 10.2 / 6 = 1.70 (above 1.65), ignoring f. The map colour steps at 1.2, 1.45 and 1.65 are illustrative and make no claim about any injury level.',
  closedPerfusion:'Illustrative numbers, not current patient data. Weighted closed share = sum of w × weighting × (1 − f) ÷ sum of w × weighting, using the open fraction f before the breath. Example: two regions of equal size. The back region has weighting 1.5 and is closed (f = 0). The front region has weighting 0.5 and is open (f = 1). Share = 0.5 × 1.5 × 1 ÷ (0.5 × 1.5 + 0.5 × 0.5) = 0.75 ÷ 1.00 = 75%, although half of the tissue is closed.',
  transrespDP:'Illustrative numbers, not current patient data. Change = (airway − external at end inspiration) − (airway − external before inspiration). Example: external −25 and −8 with airway 0 gives (0 − (−25)) − (0 − (−8)) = 25 − 8 = 17 cmH2O, equal to the matched positive-pressure plateau 25 − PEEP 8.',
  transrespCrs:'Illustrative numbers, not current patient data. Crs = delivered volume ÷ airway-minus-external pressure change. Example: 420 mL ÷ 17 cmH2O = 24.7 mL/cmH2O.',
  ppeak:'Illustrative numbers, not current patient data. Peak airway pressure = elastic part + resistive part. Example: elastic part 25 cmH2O plus central resistance 8 cmH2O·s/L × flow 0.5 L/s = 4 cmH2O gives 29 cmH2O. Regional resistances add further resistive load, and this is not a plateau measurement.',
  fractionEmptied:'Illustrative numbers, not current patient data. Extra air = gas above the relaxed volume at PEEP. This includes leftovers from earlier breaths, so it is not measured from the start of this breath. Share released = (extra at peak − extra at end) ÷ extra at peak. Example: peak extra 40 mL, start 6 mL, end 6 mL gives (40 − 6) / 40 = 34 / 40 = 85% released and 15% remaining. Expired ÷ inspired volume would be 34 / 34 = 100% even though 6 mL of extra air remains.',
  retainedVolume:'Illustrative numbers, not current patient data. Extra air left = gas at the end of the breath out − relaxed volume at PEEP, with open tissue held fixed. Not all air must leave at PEEP: the relaxed volume stays in the lung. Example: relaxed 2,000 mL and end-of-breath 2,006 mL leave 6 mL extra. A region shows a blue ring on the map when its end-expiratory extra air is more than 10% of its extra air at peak. No ring does not mean completely empty. Hypothetically, with peak extra 40 and end extra 3, 3 / 40 = 7.5% remains, no ring appears and 3 mL of extra air is still there.',
  tauEquivalent:'Illustrative numbers, not current patient data. Equivalent time constant = (R0 + 1/G) × C_input, where R0 is the central resistance, 1/G is the combined resistance of the regions in parallel and C_input is the network compliance. Example: (8 + 4) cmH2O·s/L × 0.030 L/cmH2O = 0.36 s. Doubling R0 to 16 gives (16 + 4) × 0.030 = 0.60 s, which is not double. A region’s own local RC = R_i × C_i does not contain R0, so it is unchanged when central resistance doubles.',
  complianceInput:'Illustrative numbers, not current patient data. C_input = 1 ÷ (1/sum of regional chord compliances + chest-wall elastance). A chord compliance is the volume change between two reference states divided by their pressure change. Example: tissue elastance 20 cmH2O/L plus chest wall 10 cmH2O/L = 30 cmH2O/L, so C_input = 1/30 L/cmH2O = 33 mL/cmH2O.',
  virtualEndHoldPressure:'Illustrative numbers, not current patient data. Hypothetical pressure = PEEP + extra air at end inspiration ÷ C_input. Example: 8 + 420 mL ÷ 30 mL/cmH2O = 8 + 14 = 22 cmH2O. No occlusion is simulated.',
  virtualAutoPeep:'Illustrative numbers, not current patient data. Hypothetical excess pressure = extra air at the end of the breath out ÷ C_input. Example: 60 mL ÷ 30 mL/cmH2O = 2 cmH2O. This is not a measured auto-PEEP.'
};
export const VT_DISPLAY_TOLERANCE_ML=1;
const signed=(v,n=1)=>`${v>=0?'+':''}${v.toFixed(n)}`;
export function explainComparison(before,after){
  const a=(after.openEE-before.openEE)*100,d=after.dp-before.dp,h=(after.over-before.over)*100;
  const compliance=Number.isFinite(before.crs)&&Number.isFinite(after.crs)?` compliance ${signed(after.crs-before.crs)} mL/cmH2O;`:"";
  const delivery=Number.isFinite(before.vtDelivered)&&Number.isFinite(after.vtDelivered)?` Delivered tidal volume ${before.vtDelivered.toFixed(0)} → ${after.vtDelivered.toFixed(0)} mL.`:'';
  const changes=`Open tissue before the breath ${signed(a)} percentage points; driving pressure ${signed(d)} cmH2O;${compliance} high-stretch tissue share ${signed(h)} percentage points.${delivery}`;
  const volumeKnown=Number.isFinite(before.vtDelivered)&&Number.isFinite(after.vtDelivered);
  const volumeChanged=volumeKnown&&Math.abs(after.vtDelivered-before.vtDelivered)>VT_DISPLAY_TOLERANCE_ML;
  const dpWord=d<-.5?'falls':d>.5?'rises':'changes little';
  let meaning;
  if(a>1 && h>1)meaning='More tissue is open before the breath, and more of the open tissue is also stretched past the high-stretch cutoff. This is a tradeoff between opening more lung and stretching lung that is already open.';
  else if(a<-1){
    const distension=h>1?'the high-stretch tissue share rises, so losing open tissue does not rule out more stretch in the tissue that stays open':h<-1?'the high-stretch tissue share falls':'the high-stretch tissue share changes little';
    meaning=`Open tissue before the breath is lost (derecruitment: tissue that has closed again), and ${distension}. Driving pressure ${dpWord}; read this pressure together with how much tissue is still open.`;
  }
  else if(a<=1 && h>1)meaning='Little extra tissue opens, but the high-stretch tissue share rises. Here the change mostly adds stretch to tissue that was already open.';
  else if(a>1 && d<-.5 && h<=1 && volumeKnown && !volumeChanged)meaning='More tissue is open and driving pressure falls at similar delivered volume, with little change in the high-stretch tissue share. This describes a mechanical change in the model; it does not establish clinical benefit.';
  else if(a>1 && h<=1)meaning='More tissue is open, with little change in the high-stretch tissue share. Read this together with the delivered volume and the pressures.';
  else meaning='The measures move in different directions or only slightly. Look at open tissue, delivered volume, pressure and stretch together instead of judging one number alone.';
  if(volumeChanged)meaning+=` Delivered tidal volume differs by more than ${VT_DISPLAY_TOLERANCE_ML} mL, so a change in driving pressure is not a like-for-like comparison at equal volume. Read pressure and compliance alongside the volume actually delivered and the stretch.`;
  if(before.limited||after.limited)meaning+=' The pressure ceiling was reached in at least one comparison state. Compare requested and delivered tidal volume; reduced delivered volume changes how the pressures can be interpreted.';
  return {changes,meaning,pressure:`Pressure across lung tissue at end inspiration: airway ${after.pplat.toFixed(1)} − mean pleural ${after.meanPleuralEI.toFixed(1)} = mean transpulmonary ${after.transpulmonaryEI.toFixed(1)} cmH2O (pleural pressure is the pressure around the lung). Pleural pressure changes ${(after.meanPleuralEI-after.meanPleuralEE).toFixed(1)} cmH2O within the displayed breath.`,scope:'This explains how the model responds; it does not select a clinically optimal PEEP or establish treatment benefit.'};
}

const CONTROLS = {
  peep: {label:'PEEP',unit:'cmH2O',why:'PEEP is the airway pressure left in the lungs when a breath out ends. Raising it increases the pressure pulling on lung tissue, which can open more closed tissue and can also make tissue that is already open expand further.',tradeoff:'Compare how much extra tissue opens with how much tissue becomes highly stretched. More open tissue or a lower driving pressure alone does not show that the change helped.'},
  vt: {label:'Tidal volume',unit:'mL/kg PBW',why:'Tidal volume is the amount of air requested for each breath. The model finds the pressure needed to push that volume into the tissue that is currently open, against the chest wall.',tradeoff:'Compare the volume actually delivered, driving pressure and the high-stretch tissue share. A pressure ceiling can stop the full requested volume from being delivered.'},
  rr: {label:'Respiratory rate',unit:'/min',why:'Respiratory rate sets how long each breath lasts. Inspiration takes one-third of each cycle, so a faster rate gives tissue less time to open and close over the ten simulated breaths.',tradeoff:'Open tissue can change simply because the time available changed. This model treats the breath as a series of still snapshots, so it does not calculate resisted airflow, trapped air or gas exchange.'}
};
const EXPERIMENT_DEFAULTS={'pressure-drive':'airway',posture:'supine','chest-load':0};
const EXPERIMENT_FIELDS={'pressure-drive':'drive',posture:'posture','chest-load':'chestLoad'};
const EXPERIMENT_CONTROLS={
  'pressure-drive':{label:'Pressure drive',unit:'',why:'Pressure drive sets where the breath pressure is applied. In this ideal model an external drive re-expresses the same breath: airway pressure readouts become zero and the pressure around the lung shifts lower, while pressure across lung tissue, volumes and open tissue are unchanged.',tradeoff:'Compare the pressure across lung tissue and the high-stretch tissue share rather than airway pressure alone. Airway-based plateau pressure, driving pressure and compliance are not reported for external drive.'},
  posture:{label:'Posture',unit:'',why:'Prone posture reverses and halves the assumed top-to-bottom gradient in the pressure around the lung while keeping its tissue-weighted average. Each region’s opening pressure and blood-flow weighting stay tied to its anatomical position.',tradeoff:'The result depends on the assumed gradient and on how much tissue sits near its opening or closing pressure. It can differ between lung types and does not generalize to a patient.'},
  'chest-load':{label:'Chest-wall load',unit:'cmH2O',why:'Chest-wall load is a static, uniform offset added to the pressure around the lung. It is separate from chest-wall stiffness, which is unchanged, and its effect depends on how full the lung is to start with.',tradeoff:'Compliance and driving pressure can move in either direction depending on the starting volume and how much tissue is open.'}
};
const experimentValue=(settings,key)=>{
  const flat=settings?.[key];if(flat!==undefined)return flat;
  const nested=settings?.experiment?.[EXPERIMENT_FIELDS[key]];
  return nested!==undefined?nested:EXPERIMENT_DEFAULTS[key];
};
export function lessonSettings(settings){
  const out={},experiment={};
  for(const [key,value] of Object.entries(settings||{})){
    if(EXPERIMENT_FIELDS[key])experiment[EXPERIMENT_FIELDS[key]]=value;else out[key]=value;
  }
  return Object.keys(experiment).length?{...out,experiment}:out;
}
export function flattenControls(settings){
  const flat={peep:settings?.peep,vt:settings?.vt,rr:settings?.rr};
  for(const key of Object.keys(EXPERIMENT_DEFAULTS))flat[key]=experimentValue(settings,key);
  return flat;
}
const experimentActive=flat=>Object.keys(EXPERIMENT_DEFAULTS).some(key=>flat[key]!==EXPERIMENT_DEFAULTS[key]);
function experimentConditions(before,after){
  const on=key=>before[key]!==EXPERIMENT_DEFAULTS[key]||after[key]!==EXPERIMENT_DEFAULTS[key];
  const parts=[];
  if(on('pressure-drive'))parts.push('External drive is an ideal uniform-transmission version of the matched airway-pressure breath: airway pressure readouts are zero, the external pressure is the negative of the original airway pressure, and pressure across lung tissue, volumes and open tissue are identical by construction. No circulation, abdomen or leak is modeled.');
  if(on('posture'))parts.push('Prone posture uses an assumed gradient that is reversed and half the supine size. The factor is a schematic assumption. The average pressure around the lung at the same gas volume, the opening pressures and the blood-flow weights are kept unchanged.');
  if(on('chest-load'))parts.push('Chest-wall load is a static offset in cmH2O added to the pressure around the lung, not mass or stiffness; chest-wall elastance is unchanged.');
  return parts.join(' ');
}
export function explainAdjustment(beforeSettings,afterSettings){
  const before=flattenControls(beforeSettings),after=flattenControls(afterSettings);
  const active=experimentActive(before)||experimentActive(after);
  const names=active?[...Object.keys(CONTROLS),...Object.keys(EXPERIMENT_CONTROLS)]:Object.keys(CONTROLS);
  const def=key=>CONTROLS[key]||EXPERIMENT_CONTROLS[key];
  const text=(key,v)=>`${v}${def(key).unit?' '+def(key).unit:''}`;
  const move=key=>CONTROLS[key]?`${before[key]} → ${after[key]} ${CONTROLS[key].unit}`:`${before[key]} → ${text(key,after[key])}`;
  const keys=names.filter(key=>before[key]!==after[key]);
  const changed=keys.map(key=>`${def(key).label}: ${move(key)}`);
  const held=names.filter(key=>!keys.includes(key)).map(key=>`${def(key).label} ${text(key,after[key])}`);
  const result={
    changed:changed.length?changed.join('; ')+'.':(active?'No setting or experiment control changed from baseline.':'No ventilator setting changed from baseline.'),
    held:held.length?'Held constant: '+held.join('; ')+'.':(active?'All six controls changed.':'All three ventilator controls changed.'),
    why:keys.length?keys.map(key=>def(key).why).join(' '):'These fresh seeded patients repeat the baseline settings and ten-breath exposure.',
    tradeoff:keys.length?keys.map(key=>def(key).tradeoff).join(' '):'Apply one adjustment to examine a mechanical tradeoff.',
    control:keys.length>1?'Multiple controls changed. These differences cannot be attributed to one '+(active?'adjustment':'ventilator adjustment')+'. Reset the lesson baseline to compare one variable.':'Same random seeds, body weight and starting state, with ten breaths per setting. This keeps the comparison fair but does not guarantee the lungs have settled into a steady pattern.'
  };
  if(active)result.conditions=experimentConditions(before,after);
  return result;
}

// These bands simplify the displayed prediction exercise; they are not clinical cutoffs.
const QUESTIONS={
 recruitment:{
  student:{metric:'openEE',patient:0,label:'A’s open tissue before the breath',scale:100,unit:'%',band:1,prompt:'PEEP 8 → 12: will more of A’s tissue be open when the next breath starts?',focus:'Look at the grey regions on the map: do more of them stay open when the breath ends?'},
  resident:{metric:'over',patient:1,label:'B’s high-stretch tissue share',scale:100,unit:'%',band:1,prompt:'PEEP 8 → 12: how will the share of B’s tissue that is open and highly stretched at end inspiration change?',focus:'Opening more tissue and stretching tissue that is already open can happen together. Check end inspiration.'},
  fellow:{metric:'dp',patient:0,label:'A’s driving pressure',scale:1,unit:'cmH2O',band:.5,prompt:'At the same tidal volume, how will A’s driving pressure change after the PEEP increase?',focus:'Compare the pressure cost with how much tissue is highly stretched. A whole-lung number can look better while some regions are stretched more.'}
 },
 wall:{
  student:{metric:'pplat',patient:1,label:'B’s end-inspiratory airway pressure',scale:1,unit:'cmH2O',band:.5,prompt:'B has a stiffer chest wall. When PEEP rises, how will B’s end-inspiratory airway pressure change?',focus:'Airway pressure has to push against both the lung and the chest wall.'},
  resident:{metric:'transpulmonaryEI',patient:1,label:'B vs A pressure across lung tissue',scale:1,unit:'cmH2O',band:.5,betweenPatients:true,prompt:'At matched settings, is the pressure across B’s lung tissue higher, similar or lower than A’s?',focus:'Subtract the pressure around the lung (pleural pressure) from airway pressure before judging the load on the lung. Airway pressure alone includes the chest wall too.'},
  fellow:{metric:'dp',patient:1,label:'B’s driving pressure',scale:1,unit:'cmH2O',band:.5,prompt:'At unchanged tidal volume, how will B’s driving pressure respond to the PEEP increase?',focus:'Chest-wall load changes lung volume and how much tissue is open, not just how pressure is divided between lung and chest wall.'}
 },
 volume:{
  student:{metric:'dp',patient:0,label:'A’s driving pressure',scale:1,unit:'cmH2O',band:.5,prompt:'Tidal volume 6 → 8 mL/kg: how will A’s driving pressure change?',focus:'A bigger breath asks the open lung and the chest wall to take in more volume.'},
  resident:{metric:'over',patient:0,label:'A’s high-stretch tissue share',scale:100,unit:'%',band:1,prompt:'With a larger tidal volume, how will the share of A’s tissue that is open and highly stretched at end inspiration change?',focus:'Watch the red regions at full inspiration. The extra volume may stretch tissue that is already open.'},
  fellow:{metric:'crs',patient:0,label:'A’s respiratory compliance',scale:1,unit:'mL/cmH2O',band:1,prompt:'As tidal volume rises, how will A’s respiratory compliance change?',focus:'Open regions get harder to stretch as they fill, so the volume added per cmH2O is not constant.'}
 },
 'pressure-drive':{
  student:{metric:'meanPleuralEI',patient:1,label:'B’s mean pleural pressure at inspiration',scale:1,unit:'cmH2O',band:.5,prompt:'With the same breath driven from outside the body, how will B’s average pressure around the lung change at end inspiration?',focus:'Compare where the pressure is applied: the airway stays at zero while the outside of the body carries the drive.'},
  resident:{metric:'transpulmonaryEI',patient:1,label:'B’s end-inspiratory transpulmonary pressure',scale:1,unit:'cmH2O',band:.5,prompt:'How will the pressure across B’s lung tissue at end inspiration change under external drive?',focus:'Pressure across lung tissue is airway pressure minus the pressure around the lung. Consider what shifts in both terms.'},
  fellow:{metric:'over',patient:1,label:'B’s high-stretch tissue share',scale:100,unit:'%',band:1,prompt:'Under external drive, how will the share of B’s tissue that is open and highly stretched at end inspiration change?',focus:'In this model, regional stretch follows the pressure across lung tissue.'}
 },
 prone:{
  student:{metric:'openEE',patient:0,label:'A’s open tissue before the breath',scale:100,unit:'%',band:1,prompt:'In the assumed prone state, how will the share of A’s tissue that is open before the breath change?',focus:'The assumed gradient in the pressure around the lung is reversed and halved, while each region’s opening pressure stays the same.'},
  resident:{metric:'over',patient:1,label:'B’s high-stretch tissue share',scale:100,unit:'%',band:1,prompt:'How will the share of B’s tissue that is open and highly stretched at end inspiration change in the assumed prone state?',focus:'Pressure moves between regions with the assumed gradient, while the weighted average stays the same.'},
  fellow:{metric:'transpulmonaryEI',patient:0,label:'A’s mean end-inspiratory transpulmonary pressure',scale:1,unit:'cmH2O',band:.5,prompt:'How will the average pressure across A’s lung tissue at end inspiration change?',focus:'The weighted average pressure around the lung is kept at the same gas volume, but the volume itself may shift.'}
 },
 'chest-load':{
  student:{metric:'eelv',patient:0,label:'A’s end-expiratory lung volume',scale:.001,unit:'L',band:.01,prompt:'With a static 5 cmH2O chest-wall load, how will the gas volume left in A after breathing out change?',focus:'A static push from outside lowers the pressure across the lung at the same airway pressure.'},
  resident:{metric:'openEE',patient:1,label:'B’s open tissue before the breath',scale:100,unit:'%',band:1,prompt:'How will the share of B’s tissue that is open before the breath change under the static load?',focus:'The response depends on where B’s opening pressures lie compared with the new pressure across the tissue.'},
  fellow:{metric:'dp',patient:1,label:'B’s driving pressure',scale:1,unit:'cmH2O',band:.5,prompt:'How will B’s driving pressure change under the static load?',focus:'Compliance can move either way. The load is a push on the lung, not a change in stiffness.'}
 },
 'healthy-dependent':{
  student:{metric:'openEE',patient:1,label:'B’s open tissue before the breath',scale:100,unit:'%',band:1,prompt:'PEEP 2 → 10: how will the share of B’s tissue that is open before the breath change?',focus:'B has an assumed tendency for dependent tissue to close; A does not.'},
  resident:{metric:'cyclic',patient:1,label:'B’s opening during the breath',scale:100,unit:'%',band:1,prompt:'How will the extra tissue that opens during B’s breath change after the PEEP increase?',focus:'Opening during the breath is the extra open tissue at the end of the breath compared with just before it.'},
  fellow:{metric:'dp',patient:1,label:'B’s driving pressure',scale:1,unit:'cmH2O',band:.5,prompt:'At the same tidal volume, how will B’s driving pressure change?',focus:'This is a teaching construct; dependent closure is not always present in healthy lungs.'}
 }
};
export function predictionQuestion(lesson,level='student'){
 return QUESTIONS[lesson]?.[level]||QUESTIONS.recruitment.student;
}
export function evaluatePrediction(question,before,after,prediction){
 const initial=question.betweenPatients?after[0]?.metrics[question.metric]:before[question.patient]?.metrics[question.metric];
 const final=after[question.patient]?.metrics[question.metric];
 if(!Number.isFinite(initial)||!Number.isFinite(final))return {expected:null,correct:null,observed:'This measure is unavailable for this comparison.'};
 const a=initial*question.scale,b=final*question.scale,d=b-a;
 const expected=d>question.band?'up':d<-question.band?'down':'same';
 const observed=question.betweenPatients?`${question.label}: A ${a.toFixed(1)} vs B ${b.toFixed(1)} ${question.unit}.`:`${question.label}: ${a.toFixed(1)} → ${b.toFixed(1)} ${question.unit}.`;
 return {expected,correct:['up','same','down'].includes(prediction)?prediction===expected:null,observed};
}

export const FLOW_LESSONS={
 'flow-resistance':{name:'Resistance and emptying',kinds:['high','low'],baseline:{peep:8,vt:6,rr:20,pbw:70,resistance:8},adjustment:{resistance:16},objective:'See how doubling the shared central airway resistance changes the pressure needed and how much extra air is left after the breath out, even though each region’s own RC does not change.',instruction:'Double the central airway resistance (8 → 16), the narrow shared pipe that all regions empty through, while the open tissue stays fixed. Compare the peak airway pressure, the airflow and how much extra air is left after breathing out. Extra air means gas above the relaxed volume the lungs would settle at for this PEEP.',reflection:'Each region has a local RC: its own resistance times its own compliance. Doubling the central resistance leaves every local RC unchanged, yet the shared pipe and the chest wall still couple the regions, so the actual emptying did change. Does local RC alone explain what you saw?',numbers:'Illustrative numbers, not current patient data. Extra air = gas above the relaxed volume at PEEP. This includes leftovers from earlier breaths, so it is not measured from the start of this breath. Peak extra 40 mL, start 6 mL, end 6 mL: (40 − 6) / 40 = 85% released and 15% remains. Expired ÷ inspired volume is 34 / 34 = 100%, even though 6 mL of extra air remains. Local RC = R_i × C_i has no central resistance in it, so it is unchanged when central resistance goes from 8 to 16. The shared central resistance and the chest wall still couple the regions and shape the actual emptying, so this does not mean doubling the resistance doubles the emptying time.'},
 'flow-rate':{name:'Shorter expiration',kinds:['high','low'],baseline:{peep:8,vt:6,rr:20,pbw:70,resistance:8},adjustment:{rr:30},objective:'See how a faster rate shortens both phases of the breath and leaves less time for extra air to leave.',instruction:'Raise the respiratory rate from 20 to 30 at the same requested tidal volume. Inspiration and expiration both become shorter while the open tissue stays fixed. Extra air means gas above the relaxed volume the lungs would settle at for this PEEP.',reflection:'Compare the airflow at the end of expiration with the extra air left. The lungs may not return to their relaxed PEEP volume before the next breath starts, and the extra air left includes leftovers from earlier breaths.',numbers:'Illustrative numbers, not current patient data. Breath length = 60 ÷ rate. At rate 20 the cycle is 3.0 s with 1.0 s inspiration and 2.0 s expiration. At rate 30 the cycle is 2.0 s with 0.67 s inspiration and 1.33 s expiration. For a single time constant of 1 s, the extra air left after expiration is e^(−2.0) = 14% at rate 20 and e^(−1.33) = 26% at rate 30. This one-compartment example only shows the direction of the effect. Not all air must leave at PEEP: the relaxed volume stays in the lung.'}
};
export function airflowQuestion(lesson,level='student'){
 const resistance=lesson==='flow-resistance';
 if(level==='resident')return {metric:'ppeak',patient:0,label:'A’s peak airway pressure',scale:1,unit:'cmH2O',band:.5,prompt:resistance?'Resistance 8 → 16: how will A’s peak airway pressure change?':'Rate 20 → 30: how will A’s peak airway pressure change at the same tidal volume?',focus:'Peak pressure at the airway opening includes the extra push needed to move air through resistance, so it is not a direct reading of the pressure inside each airspace. It is not a plateau measurement.'};
 if(level==='fellow')return {metric:'fractionEmptied',patient:0,label:'A’s share of extra air released',scale:100,unit:'%',band:1,prompt:resistance?'As central resistance rises, how will the share of extra air released change?':'With shorter expiration, how will the share of extra air released change?',focus:'The share is measured against the extra air at the end of the breath in, and extra air means gas above the relaxed PEEP volume. A region’s own RC is not the emptying time of the whole connected network.'};
 return {metric:'retainedVolume',patient:0,label:'A’s extra air left at the end of the breath out',scale:1,unit:'mL',band:.5,prompt:resistance?'Resistance 8 → 16: will more extra air be left after the breath out?':'Rate 20 → 30: will more extra air be left after the breath out?',focus:'Watch the airflow shrink toward zero. If air is still leaving when expiration ends, some extra air is left behind in this model. Not all air must leave at PEEP.'};
}
Object.assign(METRIC_HELP,{
 ppeak:'The highest pressure at the airway opening during the breath. It includes the extra push needed to move air through resistance, so it is not a plateau pressure.',
 fractionEmptied:'The share of the extra air at the end of the breath in that was released by the end of the breath out. Extra air means gas above the relaxed volume the lungs would settle at for this PEEP. It is not expired volume divided by inspired volume.',
 retainedVolume:'The extra air still left at the end of the breath out, above the relaxed volume for this PEEP, with open tissue held fixed. It can include leftovers from earlier breaths. It is a model quantity, not a measured clinical intrinsic PEEP.',
 tauEquivalent:'One time constant that stands in for the whole connected network, built from its combined resistance and compliance. It treats the network as a single average pipe and balloon, so it is exact only if every region were the same and it does not describe each region.',
 complianceInput:'How much volume the connected tissue and chest wall take per cmH2O, with open tissue held fixed. It is the stiffness input to the airflow experiment, not a measured dynamic compliance.',
 virtualEndHoldPressure:'A hypothetical pressure: where the airway pressure would settle if the air at the end of the breath spread evenly with no flow. No actual breath hold is simulated.',
 virtualAutoPeep:'A hypothetical pressure that the extra air left after the breath out would produce if it spread evenly with no flow. It is not a measured clinical auto-PEEP.'
});
